      - name: "Build sanitized copy (strip .github/workflows)"
        env:
          PAT: ${{ secrets.MIRROR_PAT }}
          OWNER_REPO: "Mesbah-Lab-UCB/Space-Microbial-Manufacturing-Is-A-Go"
        run: |
          set -euxo pipefail
          rm -rf sanitized
          git clone . sanitized
          cd sanitized

          # Remove all workflow files from history so no workflow scope is needed
          git filter-repo --path .github/workflows --invert-paths --force

          TARGET="https://x-access-token:${PAT}@github.com/${OWNER_REPO}.git"
          git remote add mirror "$TARGET"

          # See what's on the target (you already saw 'main' there)
          git ls-remote --heads mirror || true
          git fetch mirror --prune

          # OVERWRITE the target with the sanitized history
          git push mirror --all --force
          git push mirror --tags --force
