name: Mirror to Secondary Repo

on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history) without GITHUB_TOKEN creds
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # <— prevents github-actions[bot] creds

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Preflight: ensure secret and set remote with PAT
        env:
          PAT: ${{ secrets.MIRROR_PAT }}   # <-- make sure your secret is named exactly this
          OWNER_REPO: Mesbah-Lab-UCB/Space-Microbial-Manufacturing-Is-A-Go
        run: |
          set -euxo pipefail
          test -n "$PAT" || (echo "ERROR: Secret MIRROR_PAT is missing/empty" && exit 1)
          TARGET="https://x-access-token:${PAT}@github.com/${OWNER_REPO}.git"
          git remote rm mirror || true
          git remote add mirror "$TARGET"
          git remote -v
          git ls-remote --heads mirror   # clear error if PAT lacks access/approval

      - name: Push --mirror to target
        run: |
          set -euxo pipefail
          git push --mirror mirror
